name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [8]
        python: [3.8, 3.9, "3.10"]
    steps:
      - uses: actions/checkout@master
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          jvm: ${{ matrix.jdk }}
          apps: sbtn
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Test default Python
        run: sbt scripted
        shell: bash
      - name: Test virtualenv
        run: scripts/virtualenv_test.sh
        shell: bash
